services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: phoenix-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file: 
      - .env.docker 
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    container_name: phoenix-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  api-gateway:
    build:
      context: ./
      dockerfile: api-gateway/Dockerfile
    container_name: api-gateway
    env_file: 
      - .env.docker 
    ports:
      - "3001:3000"
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: sh -c "node -r tsconfig-paths/register dist/api-gateway/src/app.js"

  user-service:
    build:
      context: ./
      dockerfile: user-service/Dockerfile
    container_name: user-service
    env_file: 
      - .env.docker 
    ports:
      - "50051:50051"
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: sh -c "node -r tsconfig-paths/register dist/user-service/src/app.js"

  data-ingestion-service:
    build:
      context: ./
      dockerfile: data-ingestion-service/Dockerfile
    container_name: ingestion-service
    env_file: 
      - .env.docker 
    ports:
      - "50053:50053"
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: sh -c "node -r tsconfig-paths/register dist/data-ingestion-service/src/app.js"
  storage-service:
    build:
      context: ./
      dockerfile: storage-service/Dockerfile
    container_name: storage-service
    env_file: 
      - .env.docker 
    ports:
      - "50054:50054"
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: sh -c "node -r tsconfig-paths/register dist/storage-service/src/app.js"
